### PR TITLE
feat: use on_events config for custom eventing

### PR DESCRIPTION
**Pull request by cmgriffing**
This adds a config option for custom event listening.

`on_events` is the config option and it takes a comma separated list of vim events. (no spaces)

### CODE REVIEW

**Comment by cmgriffing** [comment]
@elianiva This is the PR that I was mentioning I would make in a comment on your previous on_insert_event PR.

**Comment by elianiva** [comment]
This one seems better as it provides a more fine grained control over the events, I like it! :)

**Comment by cmgriffing** [comment]
Hmm, I like the table idea too. I will double check with my stream viewers and see what they think too.

**Comment by cmgriffing** [comment]
Ok cool, I think this does it. Table based config instead. I am going to merge and let me know if you have any issues.

**Pull request merged**
