### PR TITLE
feat: add option for only showing biscuits on the current cursor line

### PR DESCRIPTION
**Pull request by cmgriffing**
JerseyMilker on Twitch asked for this feature and I think it makes a lot of sense.
It really helps cut down on the clutter.

### CODE REVIEW

**Comment by jesseleite** [comment]
You are my hero.

**Comment by jesseleite** [comment]
Ah, found another thing since your stream. It seems when `cursor_line_only = true`, as soon as I move the cursor, all of Neovim's LSP inline diagnostics disappear 🤔

CleanShot 2021-07-14 at 22 31 25

**Comment by cmgriffing** [comment]
Interesting. My guess is that its because of the highlight group I am using.

We can look into that soon.

**Comment by cmgriffing** [comment]
@jesseleite Try it again with the latest changes. I believe its fixed now.

**Comment by jesseleite** [comment]
@cmgriffing Works beauty!

**Pull request merged**
